/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { NextPage } from "next";
import { useRouter } from "next/dist/client/router";
import { useEffect, useState } from "react";
import { getArtObject } from "../../utils/api";
import { ArtObject } from "../../utils/types";
import ArtDescription from "../../components/ArtDescription";
import Header from "../../components/Header";
import { Notification } from "../../components/Notification";
import { EmptyState } from "../../components/EmptyState";
import styles from "../../styles/pages/art-post.module.css";

const ArtPost: NextPage = () => {
  //Grabbing query parameter by referring to path :objectId
  const router = useRouter();
  const objectId = router.query.objectId;

  const [artObject, setArtObject] = useState<ArtObject>();
  const [error, setError] = useState<any>();
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    async function fetchArtObject() {
      if (objectId && objectId !== "undefined") {
        setIsLoading(true);
        try {
          const id = parseInt(objectId as string);
          const artObject = await getArtObject(id);
          setArtObject(artObject);
        } catch (error) {
          setError("Couldn't fetch art object.");
        }
        setIsLoading(false);
      }
    }
    fetchArtObject();
  }, [objectId]);

  return (
    <div className={styles.art_post}>
      <Head>
        <title>Art Crawl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {error && (
        <Notification
          isError={true}
          message={error}
          onClose={() => setError(null)}
        />
      )}
      <main className={styles.post_items}>
        {artObject?.imageSource && (
          <img src={artObject.imageSource} alt={artObject.title} />
        )}
        {artObject && !isLoading && !error && (
          <div className={styles.description_info}>
            <ArtDescription artObject={artObject} />
          </div>
        )}
        {!artObject && !isLoading && (
          <EmptyState
            message="No art object found."
            secondaryMessage="Please try refreshing the page, or return to Home."
          />
        )}
      </main>
      {isLoading && <div className={styles.loader}></div>}
    </div>
  );
};

export default ArtPost;
