import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useContext, useEffect, useState } from "react";
import styles from "../styles/WelcomePage.module.css";
import ObjectsContext from "../context/objects-context";
import { getArtObject, getArtObjects } from "../utils/api";
import { useFavorites } from "../hooks/use-favorites";
import { ArtObject } from "../utils/types";
import { RightArrowIcon } from "../assets/RightArrowIcon";

const WelcomePage: NextPage = () => {
  const [artObjects, setArtObjects] = useState<ArtObject[]>([]);
  const [favorites] = useFavorites();
  const objectsContext = useContext(ObjectsContext);
  const objectIds: number[] = objectsContext.objectIds;

  useEffect(() => {
    let newObjects: ArtObject[] = [];
    if (favorites.length >= 2) {
      newObjects = favorites
        .filter((favorite: ArtObject) => favorite.imageSource)
        .slice(0, 2);
    }

    const getObjects = async () => {
      let objects: ArtObject[] = [];
      let indexes: number[] = [];
      for (let i = 0; i < 2; i++) {
        let newIndex = Math.floor(Math.random() * (objectIds.length - 0 + 1));
        if (!indexes.some((index) => index === newIndex)) {
          newIndex = Math.floor(Math.random() * (newIndex - 0 + 1));
        }
        indexes.push(newIndex);
      }
      const newObjectIds = indexes.map((index) => objectIds[index]);
      try {
        objects = await getArtObjects(newObjectIds);
        setArtObjects(objects);
      } catch (error) {
        console.log((error as Error).message ?? "Couldn't fetch art objects.");
      }
    };

    if (newObjects.length < 2 && objectIds.length) {
      getObjects();
    } else {
      setArtObjects(newObjects);
    }
  }, [favorites, objectIds]);

  useEffect(() => {
    const replaceImagelessObject = async () => {
      const indexToReplace = artObjects.findIndex(
        (object) => !object.imageSource
      );
      let newObjectId =
        objectIds[Math.floor(Math.random() * (objectIds.length - 0 + 1))];
      try {
        let newObject = await getArtObject(newObjectId);
        if (newObject) {
          setArtObjects((prevArray) => {
            let newArray = [...prevArray];
            newArray[indexToReplace] = newObject!;
            return newArray;
          });
        }
      } catch (error) {
        console.log((error as Error).message ?? "Couldn't fetch art objects.");
      }
    };
    if (
      objectIds.length > 0 &&
      artObjects.length >= 2 &&
      artObjects.some((object) => !object.imageSource)
    ) {
      replaceImagelessObject();
    }
  }, [artObjects, objectIds]);

  return (
    <div>
      <Head>
        <title>Art Crawl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <html lang="en"></html> */}
      </Head>
      <main className={styles.main}>
        <div className={styles.images}>
          <div className={styles.primary_image_frame}>
            <div className={styles.primary_cropped_image}>
              {artObjects[0]?.imageSource ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={artObjects[0].imageSource}
                  alt={artObjects[0].title}
                  className={styles.primary_image}
                />
              ) : (
                <div className={styles.primary_image}></div>
              )}
            </div>
          </div>
          <div className={styles.secondary_image_frame}>
            <div className={styles.secondary_cropped_image}>
              {artObjects[1]?.imageSource ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={artObjects[1].imageSource}
                  alt={artObjects[1].title}
                  className={styles.secondary_image}
                />
              ) : (
                <div className={styles.secondary_image}></div>
              )}
            </div>
          </div>
        </div>

        <div className={styles.main_text}>
          <h1>Art Crawl</h1>
          <h2>
            Explore a variety of pieces at the Metropolitan Museum of Art.
          </h2>
          <Link href="/home">
            <a>
              Get Started
              <RightArrowIcon />
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default WelcomePage;
